repos:
-   repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
    - id: black
      language_version: python3.8
      types: [python]
      exclude: "setup.py"
-   repo: local
    hooks:
    - id: export_setup_py
      name: export_setup_py
      entry: "poetry run python ./create_setup.py"
      language: system
      files: "pyproject.toml"
    - id: pytest
      name: pytest
      language: system
      entry: pytest
      pass_filenames: false
      always_run: true
      stages: [push]
