[tool.poetry]
name = "unweaver"
version = "0.1.0"
description = "A flexible, easy to run routing engine."
authors = ["Nick Bolten <nbolten@gmail.com>"]
license = "MIT"

[tool.poetry.scripts]
unweaver = "unweaver:cli.unweaver"

[tool.poetry.dependencies]
python = "^3.6"
flask = "^1.0"
webargs = "^5.3"
click = "^7.0"
entwiner = {git = "https://github.com/nbolten/entwiner.git", rev = "fd9c1af"}
shapely = "^1.6"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
black = "18.9b0"
pre-commit = "^1.14"

[tool.black]
exclude = """
(
  setup.py
)
"""

[tool.dephell.main]
from = {format = "poetry", path = "pyproject.toml"}
to = {format = "setuppy", path = "setup.py"}

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
